# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_worked', models.IntegerField()),
                ('total_hours_break', models.IntegerField()),
                ('submission_date', models.DateTimeField(verbose_name='Date the timesheet was submitted by the employee')),
                ('approval_date', models.DateTimeField(verbose_name='Date the timesheet was approved by the Approving Manager')),
            ],
        ),
    ]
